#!/bin/sh

# yadm clone --bootstrap git@github.com:FrankFang/dotfiles.git

# https://yadm.io/docs/bootstrap#

system_type=$(uname -s)
repo="git@github.com:FrankFang/dotfiles.git"

echo "Updating the yadm repo origin URL"
yadm remote set-url origin $repo

yes | sudo pacman -Syy
yes | sudo pacman -S zsh
chsh -s /bin/zsh

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

fi

